---
#########################################################################
# Config file for metatranscriptomics data analysis on IFB core cluster #
# Author : Domitille Jarrige                                            #
# Date   : 2025-03-13                                                   #
#########################################################################

parameters:
    threads: 12
    memory: 4
data_directory:
    data/raw/RNAseq_2022-09-16_new_names/
quality_control_directory:
    results/QC/
cleaning_directory:
    results/cleaning/
human_genome_index_prefix:
    /shared/data/bank/homo_sapiens/GRCh38/bwa/Homo_sapiens.GRCh38.dna.primary_assembly.fa # to filter contaminating sequences
genome_fasta_directory:
    data/ref_genomes/assemblies/
genome_gff_directory:
    data/ref_genomes/annotations/
genome_index_directory:
    data/ref_genomes/indexes/
filtering_directory:
    results/filtering/
rrna_directory:
    results/filtering/rRNA/
mapping_directory:
    results/star_mapping/
counts_directory:
    results/counts/
rRNA_database:  
    data/ref_genomes/rRNA_database.fasta
...
